/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyCategory = IDL.Variant({
  'Commercial' : IDL.Null,
  'Plot' : IDL.Null,
  'BuilderFloor' : IDL.Null,
  'Villa' : IDL.Null,
  'Apartment' : IDL.Null,
});
export const TargetBuyer = IDL.Variant({
  'Investor' : IDL.Null,
  'PremiumBuyer' : IDL.Null,
  'EndUser' : IDL.Null,
});
export const Furnishing = IDL.Variant({
  'Furnished' : IDL.Null,
  'SemiFurnished' : IDL.Null,
  'Unfurnished' : IDL.Null,
});
export const Representation = IDL.Variant({
  'ChannelPartner' : IDL.Null,
  'Broker' : IDL.Null,
  'Owner' : IDL.Null,
});
export const PropertySubmission = IDL.Record({
  'locationAdvantages' : IDL.Text,
  'propertyCategory' : PropertyCategory,
  'projectName' : IDL.Text,
  'clientName' : IDL.Text,
  'askingPrice' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'targetBuyer' : TargetBuyer,
  'floorDetails' : IDL.Text,
  'connectivity' : IDL.Text,
  'submittedAt' : IDL.Int,
  'authorized' : IDL.Bool,
  'keyHighlights' : IDL.Text,
  'email' : IDL.Text,
  'propertyAge' : IDL.Text,
  'contactNumber' : IDL.Text,
  'configuration' : IDL.Text,
  'fullAddress' : IDL.Text,
  'priceJustification' : IDL.Text,
  'uniqueFeatures' : IDL.Text,
  'furnishing' : Furnishing,
  'location' : IDL.Text,
  'representation' : Representation,
  'negotiable' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getSubmissions' : IDL.Func([], [IDL.Vec(PropertySubmission)], ['query']),
  'submitProperty' : IDL.Func([PropertySubmission], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyCategory = IDL.Variant({
    'Commercial' : IDL.Null,
    'Plot' : IDL.Null,
    'BuilderFloor' : IDL.Null,
    'Villa' : IDL.Null,
    'Apartment' : IDL.Null,
  });
  const TargetBuyer = IDL.Variant({
    'Investor' : IDL.Null,
    'PremiumBuyer' : IDL.Null,
    'EndUser' : IDL.Null,
  });
  const Furnishing = IDL.Variant({
    'Furnished' : IDL.Null,
    'SemiFurnished' : IDL.Null,
    'Unfurnished' : IDL.Null,
  });
  const Representation = IDL.Variant({
    'ChannelPartner' : IDL.Null,
    'Broker' : IDL.Null,
    'Owner' : IDL.Null,
  });
  const PropertySubmission = IDL.Record({
    'locationAdvantages' : IDL.Text,
    'propertyCategory' : PropertyCategory,
    'projectName' : IDL.Text,
    'clientName' : IDL.Text,
    'askingPrice' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'targetBuyer' : TargetBuyer,
    'floorDetails' : IDL.Text,
    'connectivity' : IDL.Text,
    'submittedAt' : IDL.Int,
    'authorized' : IDL.Bool,
    'keyHighlights' : IDL.Text,
    'email' : IDL.Text,
    'propertyAge' : IDL.Text,
    'contactNumber' : IDL.Text,
    'configuration' : IDL.Text,
    'fullAddress' : IDL.Text,
    'priceJustification' : IDL.Text,
    'uniqueFeatures' : IDL.Text,
    'furnishing' : Furnishing,
    'location' : IDL.Text,
    'representation' : Representation,
    'negotiable' : IDL.Bool,
  });
  
  return IDL.Service({
    'getSubmissions' : IDL.Func([], [IDL.Vec(PropertySubmission)], ['query']),
    'submitProperty' : IDL.Func([PropertySubmission], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };