/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Furnishing = { 'Furnished' : null } |
  { 'SemiFurnished' : null } |
  { 'Unfurnished' : null };
export type PropertyCategory = { 'Commercial' : null } |
  { 'Plot' : null } |
  { 'BuilderFloor' : null } |
  { 'Villa' : null } |
  { 'Apartment' : null };
export interface PropertySubmission {
  'locationAdvantages' : string,
  'propertyCategory' : PropertyCategory,
  'projectName' : string,
  'clientName' : string,
  'askingPrice' : string,
  'area' : string,
  'city' : string,
  'targetBuyer' : TargetBuyer,
  'floorDetails' : string,
  'connectivity' : string,
  'submittedAt' : bigint,
  'authorized' : boolean,
  'keyHighlights' : string,
  'email' : string,
  'propertyAge' : string,
  'contactNumber' : string,
  'configuration' : string,
  'fullAddress' : string,
  'priceJustification' : string,
  'uniqueFeatures' : string,
  'furnishing' : Furnishing,
  'location' : string,
  'representation' : Representation,
  'negotiable' : boolean,
}
export type Representation = { 'ChannelPartner' : null } |
  { 'Broker' : null } |
  { 'Owner' : null };
export type TargetBuyer = { 'Investor' : null } |
  { 'PremiumBuyer' : null } |
  { 'EndUser' : null };
export interface _SERVICE {
  'getSubmissions' : ActorMethod<[], Array<PropertySubmission>>,
  'submitProperty' : ActorMethod<[PropertySubmission], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];