/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PropertySubmission {
    locationAdvantages: string;
    propertyCategory: PropertyCategory;
    projectName: string;
    clientName: string;
    askingPrice: string;
    area: string;
    city: string;
    targetBuyer: TargetBuyer;
    floorDetails: string;
    connectivity: string;
    submittedAt: bigint;
    authorized: boolean;
    keyHighlights: string;
    email: string;
    propertyAge: string;
    contactNumber: string;
    configuration: string;
    fullAddress: string;
    priceJustification: string;
    uniqueFeatures: string;
    furnishing: Furnishing;
    location: string;
    representation: Representation;
    negotiable: boolean;
}
export enum Furnishing {
    Furnished = "Furnished",
    SemiFurnished = "SemiFurnished",
    Unfurnished = "Unfurnished"
}
export enum PropertyCategory {
    Commercial = "Commercial",
    Plot = "Plot",
    BuilderFloor = "BuilderFloor",
    Villa = "Villa",
    Apartment = "Apartment"
}
export enum Representation {
    ChannelPartner = "ChannelPartner",
    Broker = "Broker",
    Owner = "Owner"
}
export enum TargetBuyer {
    Investor = "Investor",
    PremiumBuyer = "PremiumBuyer",
    EndUser = "EndUser"
}
export interface backendInterface {
    getSubmissions(): Promise<Array<PropertySubmission>>;
    submitProperty(submission: PropertySubmission): Promise<string>;
}
import type { Furnishing as _Furnishing, PropertyCategory as _PropertyCategory, PropertySubmission as _PropertySubmission, Representation as _Representation, TargetBuyer as _TargetBuyer } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getSubmissions(): Promise<Array<PropertySubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitProperty(arg0: PropertySubmission): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProperty(to_candid_PropertySubmission_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProperty(to_candid_PropertySubmission_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Furnishing_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Furnishing): Furnishing {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyCategory): PropertyCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PropertySubmission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertySubmission): PropertySubmission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Representation_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Representation): Representation {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TargetBuyer_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TargetBuyer): TargetBuyer {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationAdvantages: string;
    propertyCategory: _PropertyCategory;
    projectName: string;
    clientName: string;
    askingPrice: string;
    area: string;
    city: string;
    targetBuyer: _TargetBuyer;
    floorDetails: string;
    connectivity: string;
    submittedAt: bigint;
    authorized: boolean;
    keyHighlights: string;
    email: string;
    propertyAge: string;
    contactNumber: string;
    configuration: string;
    fullAddress: string;
    priceJustification: string;
    uniqueFeatures: string;
    furnishing: _Furnishing;
    location: string;
    representation: _Representation;
    negotiable: boolean;
}): {
    locationAdvantages: string;
    propertyCategory: PropertyCategory;
    projectName: string;
    clientName: string;
    askingPrice: string;
    area: string;
    city: string;
    targetBuyer: TargetBuyer;
    floorDetails: string;
    connectivity: string;
    submittedAt: bigint;
    authorized: boolean;
    keyHighlights: string;
    email: string;
    propertyAge: string;
    contactNumber: string;
    configuration: string;
    fullAddress: string;
    priceJustification: string;
    uniqueFeatures: string;
    furnishing: Furnishing;
    location: string;
    representation: Representation;
    negotiable: boolean;
} {
    return {
        locationAdvantages: value.locationAdvantages,
        propertyCategory: from_candid_PropertyCategory_n4(_uploadFile, _downloadFile, value.propertyCategory),
        projectName: value.projectName,
        clientName: value.clientName,
        askingPrice: value.askingPrice,
        area: value.area,
        city: value.city,
        targetBuyer: from_candid_TargetBuyer_n6(_uploadFile, _downloadFile, value.targetBuyer),
        floorDetails: value.floorDetails,
        connectivity: value.connectivity,
        submittedAt: value.submittedAt,
        authorized: value.authorized,
        keyHighlights: value.keyHighlights,
        email: value.email,
        propertyAge: value.propertyAge,
        contactNumber: value.contactNumber,
        configuration: value.configuration,
        fullAddress: value.fullAddress,
        priceJustification: value.priceJustification,
        uniqueFeatures: value.uniqueFeatures,
        furnishing: from_candid_Furnishing_n8(_uploadFile, _downloadFile, value.furnishing),
        location: value.location,
        representation: from_candid_Representation_n10(_uploadFile, _downloadFile, value.representation),
        negotiable: value.negotiable
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ChannelPartner: null;
} | {
    Broker: null;
} | {
    Owner: null;
}): Representation {
    return "ChannelPartner" in value ? Representation.ChannelPartner : "Broker" in value ? Representation.Broker : "Owner" in value ? Representation.Owner : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Commercial: null;
} | {
    Plot: null;
} | {
    BuilderFloor: null;
} | {
    Villa: null;
} | {
    Apartment: null;
}): PropertyCategory {
    return "Commercial" in value ? PropertyCategory.Commercial : "Plot" in value ? PropertyCategory.Plot : "BuilderFloor" in value ? PropertyCategory.BuilderFloor : "Villa" in value ? PropertyCategory.Villa : "Apartment" in value ? PropertyCategory.Apartment : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Investor: null;
} | {
    PremiumBuyer: null;
} | {
    EndUser: null;
}): TargetBuyer {
    return "Investor" in value ? TargetBuyer.Investor : "PremiumBuyer" in value ? TargetBuyer.PremiumBuyer : "EndUser" in value ? TargetBuyer.EndUser : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Furnished: null;
} | {
    SemiFurnished: null;
} | {
    Unfurnished: null;
}): Furnishing {
    return "Furnished" in value ? Furnishing.Furnished : "SemiFurnished" in value ? Furnishing.SemiFurnished : "Unfurnished" in value ? Furnishing.Unfurnished : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertySubmission>): Array<PropertySubmission> {
    return value.map((x)=>from_candid_PropertySubmission_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Furnishing_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Furnishing): _Furnishing {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyCategory): _PropertyCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PropertySubmission_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertySubmission): _PropertySubmission {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Representation_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Representation): _Representation {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_TargetBuyer_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetBuyer): _TargetBuyer {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationAdvantages: string;
    propertyCategory: PropertyCategory;
    projectName: string;
    clientName: string;
    askingPrice: string;
    area: string;
    city: string;
    targetBuyer: TargetBuyer;
    floorDetails: string;
    connectivity: string;
    submittedAt: bigint;
    authorized: boolean;
    keyHighlights: string;
    email: string;
    propertyAge: string;
    contactNumber: string;
    configuration: string;
    fullAddress: string;
    priceJustification: string;
    uniqueFeatures: string;
    furnishing: Furnishing;
    location: string;
    representation: Representation;
    negotiable: boolean;
}): {
    locationAdvantages: string;
    propertyCategory: _PropertyCategory;
    projectName: string;
    clientName: string;
    askingPrice: string;
    area: string;
    city: string;
    targetBuyer: _TargetBuyer;
    floorDetails: string;
    connectivity: string;
    submittedAt: bigint;
    authorized: boolean;
    keyHighlights: string;
    email: string;
    propertyAge: string;
    contactNumber: string;
    configuration: string;
    fullAddress: string;
    priceJustification: string;
    uniqueFeatures: string;
    furnishing: _Furnishing;
    location: string;
    representation: _Representation;
    negotiable: boolean;
} {
    return {
        locationAdvantages: value.locationAdvantages,
        propertyCategory: to_candid_PropertyCategory_n14(_uploadFile, _downloadFile, value.propertyCategory),
        projectName: value.projectName,
        clientName: value.clientName,
        askingPrice: value.askingPrice,
        area: value.area,
        city: value.city,
        targetBuyer: to_candid_TargetBuyer_n16(_uploadFile, _downloadFile, value.targetBuyer),
        floorDetails: value.floorDetails,
        connectivity: value.connectivity,
        submittedAt: value.submittedAt,
        authorized: value.authorized,
        keyHighlights: value.keyHighlights,
        email: value.email,
        propertyAge: value.propertyAge,
        contactNumber: value.contactNumber,
        configuration: value.configuration,
        fullAddress: value.fullAddress,
        priceJustification: value.priceJustification,
        uniqueFeatures: value.uniqueFeatures,
        furnishing: to_candid_Furnishing_n18(_uploadFile, _downloadFile, value.furnishing),
        location: value.location,
        representation: to_candid_Representation_n20(_uploadFile, _downloadFile, value.representation),
        negotiable: value.negotiable
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyCategory): {
    Commercial: null;
} | {
    Plot: null;
} | {
    BuilderFloor: null;
} | {
    Villa: null;
} | {
    Apartment: null;
} {
    return value == PropertyCategory.Commercial ? {
        Commercial: null
    } : value == PropertyCategory.Plot ? {
        Plot: null
    } : value == PropertyCategory.BuilderFloor ? {
        BuilderFloor: null
    } : value == PropertyCategory.Villa ? {
        Villa: null
    } : value == PropertyCategory.Apartment ? {
        Apartment: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetBuyer): {
    Investor: null;
} | {
    PremiumBuyer: null;
} | {
    EndUser: null;
} {
    return value == TargetBuyer.Investor ? {
        Investor: null
    } : value == TargetBuyer.PremiumBuyer ? {
        PremiumBuyer: null
    } : value == TargetBuyer.EndUser ? {
        EndUser: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Furnishing): {
    Furnished: null;
} | {
    SemiFurnished: null;
} | {
    Unfurnished: null;
} {
    return value == Furnishing.Furnished ? {
        Furnished: null
    } : value == Furnishing.SemiFurnished ? {
        SemiFurnished: null
    } : value == Furnishing.Unfurnished ? {
        Unfurnished: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Representation): {
    ChannelPartner: null;
} | {
    Broker: null;
} | {
    Owner: null;
} {
    return value == Representation.ChannelPartner ? {
        ChannelPartner: null
    } : value == Representation.Broker ? {
        Broker: null
    } : value == Representation.Owner ? {
        Owner: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
